name: local-rag-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit==1.49.1
      - python-dotenv==1.1.1
      - langchain==0.3.27
      - langchain-ollama==0.3.7
      - langchain-community==0.3.29
      - langchain-chroma==0.2.5
      - langchain-text-splitters==0.3.10
      - chromadb==1.0.20
      - pypdf==6.0.0
      - ollama==0.5.3
      - beautifulsoup4
      - requests
      - lxml
